### ISSUE TITLE
Add settings for more flexibility

### ISSUE THREAD

**Issue by HeyNight0712** [Azlagor322/LiteFish#1]
Can a file folder be generated for him and the text can be customized

ex:
plugin/LiteFish/LiteFish.json
plugin/LiteFish/message.json

and 
Set the number of intermediate runs 10 -> x
![image](https://github.com/Azlagor322/LiteFish/assets/97263430/2e21e2a9-25f0-4c45-a5a9-dfda36967acb)

**Comment by Azlagor322** [comment]
If you are talking about costomization, then it is implemented in the config
<img width="174" alt="image" src="https://github.com/Azlagor322/LiteFish/assets/136051831/55c015ab-e58e-4c07-8877-2337a3cb0425">

**Comment by Azlagor322** [comment]
added in version 1.0.11
