### ISSUE TITLE
Command to open sell GUI for player as console

### ISSUE THREAD

**Issue by dat-ho** [Azlagor322/LiteFish#10]
Hi there,

Would you mind adding a command that allows us to open the GUI for players? lfish shop [player] or something.

So we can then attach the command to Citizen NPC, so players will have to come to the NPC to sell fish 🙂

Thank you,

**Comment by Azlagor322** [comment]
Hello! I have already received a request in Discord and will definitely add this command in the next updates!

**Comment by Azlagor322** [comment]
Added in version 3.3.6
