### ISSUE TITLE
can't add trasures

### ISSUE THREAD

**Issue by Reagin4ik** [Azlagor322/LiteFish#12]
![image](https://github.com/Azlagor322/LiteFish/assets/173607643/9f388ff4-3401-4331-bcff-e2cc137be4d5)

where button for add groups id and treasures? (Newest version)

**Comment by Reagin4ik** [comment]
![image](https://github.com/Azlagor322/LiteFish/assets/173607643/6eec6525-0398-4f28-a754-dec8fecf47d6)
screenshot on old version

**Comment by Azlagor322** [comment]
oh, sorry. an error occurred and I did not add icons to the new pages. I will fix this in the next version!
