### ISSUE TITLE
discord link is invalid

### ISSUE THREAD

**Issue by shamgamer** [Azlagor322/LiteFish#8]
make a new link pls

**Comment by Azlagor322** [comment]
https://discord.gg/PgDfrQx22f

I checked the link on Github. It works for me, perhaps you are experiencing temporary outages on the Discord servers

**Comment by shamgamer** [comment]
![image](https://github.com/Azlagor322/LiteFish/assets/63604663/e8d8d628-6425-4fc0-a078-eb8a2a777b47)
tried some other methods seems like joining via this spesific link just doesn't work on chrome, the discord join server worked
